version: '3.8'

services:
  userstest:
      build: .
      container_name: messengertest
      restart: unless-stopped
      environment:
        DB_HOST: host.docker.internal
        DB_PORT: 5431
        DB_USER: postgres
        DB_PASSWORD: 123
        DB_NAME: bubble
      ports:
        - "8086:8086"